# Generated by Django 6.0.3 on 2026-06-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('susep_code', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
                'indexes': [
                    models.Index(
                        fields=['brokerage', 'is_active'],
                        name='insurers_in_brokera_cb331a_idx',
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('brokerage', 'name'),
                        name='insurer_unique_name_per_brokerage',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, help_text='Código SUSEP', max_length=20)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('auto', 'Automóvel'),
                            ('life', 'Vida'),
                            ('property', 'Patrimonial'),
                            ('business', 'Empresarial'),
                            ('travel', 'Viagem'),
                            ('health', 'Saúde'),
                            ('other', 'Outros'),
                        ],
                        default='other',
                        max_length=12,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ramo',
                'verbose_name_plural': 'ramos',
                'ordering': ('name',),
                'indexes': [
                    models.Index(
                        fields=['brokerage', 'is_active'],
                        name='insurers_li_brokera_96c13f_idx',
                    ),
                    models.Index(
                        fields=['brokerage', 'category'],
                        name='insurers_li_brokera_39e769_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('brokerage', 'name'),
                        name='lob_unique_name_per_brokerage',
                    )
                ],
            },
        ),
    ]
