# Generated by Django 6.0.3 on 2026-06-28 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('insurers', '0001_initial'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(max_length=40)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Ativa'),
                            ('canceled', 'Cancelada'),
                            ('expired', 'Expirada'),
                            ('renewed', 'Renovada'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='policies',
                        to='clients.client',
                    ),
                ),
                (
                    'insurer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='policies',
                        to='insurers.insurer',
                    ),
                ),
                (
                    'line_of_business',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='policies',
                        to='insurers.lineofbusiness',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Rascunho'),
                            ('sent', 'Enviada'),
                            ('under_analysis', 'Em análise'),
                            ('approved', 'Aprovada'),
                            ('rejected', 'Recusada'),
                            ('converted', 'Convertida em apólice'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('net_premium', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_premium', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iof', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('proposed_end_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                (
                    'ai_summary_status',
                    models.CharField(
                        choices=[
                            ('idle', 'Pendente'),
                            ('processing', 'Processando'),
                            ('done', 'Concluído'),
                            ('error', 'Erro'),
                        ],
                        default='idle',
                        max_length=12,
                    ),
                ),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='proposals',
                        to='clients.client',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='proposals_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'insurer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='proposals',
                        to='insurers.insurer',
                    ),
                ),
                (
                    'line_of_business',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='proposals',
                        to='insurers.lineofbusiness',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CoveredItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'item_type',
                    models.CharField(
                        choices=[
                            ('auto', 'Automóvel'),
                            ('property', 'Imóvel'),
                            ('fleet', 'Frota'),
                            ('travel', 'Viagem'),
                            ('life', 'Vida'),
                            ('equipment', 'Equipamento'),
                            ('other', 'Outro'),
                        ],
                        default='other',
                        max_length=12,
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                (
                    'identifier',
                    models.CharField(
                        blank=True,
                        help_text='Placa, endereço, CPF/CNPJ etc.',
                        max_length=120,
                    ),
                ),
                (
                    'insured_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                    ),
                ),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('coverages', models.JSONField(blank=True, default=list)),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='covered_items',
                        to='insurance.policy',
                    ),
                ),
                (
                    'proposal',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='covered_items',
                        to='insurance.proposal',
                    ),
                ),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(
                fields=('brokerage', 'policy_number'),
                name='policy_unique_number_per_brokerage',
            ),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(
                fields=['brokerage', 'status'],
                name='insurance_p_brokera_840791_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(
                fields=['brokerage', '-created_at'],
                name='insurance_p_brokera_d5b594_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(
                fields=('brokerage', 'number'),
                name='proposal_unique_number_per_brokerage',
            ),
        ),
    ]
