# Generated by Django 6.0.3 on 2026-06-30 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('insurance', '0001_initial'),
        ('insurers', '0001_initial'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='ai_summary_status',
            field=models.CharField(choices=[('idle', 'Pendente'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Percentual da comissão paga pela seguradora à corretora.', max_digits=6),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='iof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='policy',
            name='net_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='policy',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_policies', to='insurance.proposal'),
        ),
        migrations.AddField(
            model_name='policy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='total_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', 'status'], name='insurance_p_brokera_71474a_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['brokerage', '-created_at'], name='insurance_p_brokera_090665_idx'),
        ),
    ]
