# Generated by Django 6.0.3 on 2026-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_policy_ai_summary_policy_ai_summary_status_and_more'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='covereditem',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('policy__isnull', True),
                        ('proposal__isnull', False),
                    ),
                    models.Q(
                        ('policy__isnull', False),
                        ('proposal__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='covered_item_exactly_one_parent',
            ),
        ),
    ]
