# Generated by Django 6.0.3 on 2026-06-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_covereditem_covered_item_exactly_one_parent'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsement_number', models.CharField(max_length=40)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('increase', 'Aumento de cobertura'),
                            ('decrease', 'Redução de cobertura'),
                            ('cancellation', 'Cancelamento'),
                            ('data_change', 'Alteração de dados'),
                        ],
                        default='data_change',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Rascunho'),
                            ('submitted', 'Enviado à seguradora'),
                            ('approved', 'Aprovado'),
                            ('rejected', 'Recusado'),
                            ('effective', 'Em vigor'),
                            ('canceled', 'Cancelado'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                (
                    'premium_change',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text=(
                            'Positivo para aumento, negativo para redução, '
                            'zero para alteração de dados.'
                        ),
                        max_digits=14,
                    ),
                ),
                ('effective_date', models.DateField()),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='endorsements_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='endorsements',
                        to='insurance.policy',
                    ),
                ),
            ],
            options={
                'ordering': ('-effective_date',),
                'indexes': [
                    models.Index(
                        fields=['brokerage', 'status'],
                        name='insurance_e_brokera_ee1c1e_idx',
                    ),
                    models.Index(
                        fields=['brokerage', '-effective_date'],
                        name='insurance_e_brokera_a3a34a_idx',
                    ),
                    models.Index(
                        fields=['policy', '-effective_date'],
                        name='insurance_e_policy__5c474c_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('brokerage', 'endorsement_number'),
                        name='endorsement_unique_number_per_brokerage',
                    ),
                ],
            },
        ),
    ]
