# Generated by Django 6.0.3 on 2026-07-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('person', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='person', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('susep_code', models.CharField(blank=True, max_length=30)),
                ('default_commission_rate', models.DecimalField(decimal_places=4, default=0, help_text='Percentual padrão de repasse ao agente (ex.: 0.10 = 10%).', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.brokerage')),
                ('user', models.ForeignKey(blank=True, help_text='Vincule um usuário se o agente terá login na plataforma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('person', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='person', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('document', models.CharField(max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('default_commission_rate', models.DecimalField(decimal_places=4, default=0, help_text='Percentual padrão de repasse ao produtor.', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Vincule um agente ou deixe em branco para produtor direto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='partners.agent')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.brokerage')),
                ('user', models.ForeignKey(blank=True, help_text='Vincule um usuário se o produtor terá login na plataforma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['brokerage', 'is_active'], name='partners_ag_brokera_5ecc34_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('brokerage', 'document'), name='agent_unique_document_per_brokerage'),
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['brokerage', 'is_active'], name='partners_pr_brokera_a9c6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='producer',
            index=models.Index(fields=['brokerage', 'agent'], name='partners_pr_brokera_7854a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(fields=('brokerage', 'document'), name='producer_unique_document_per_brokerage'),
        ),
    ]
