# Generated by Django 6.0.3 on 2026-06-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Ativa'),
                            ('past_due', 'Pendente'),
                            ('canceled', 'Cancelada'),
                        ],
                        default='active',
                        max_length=10,
                    ),
                ),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                (
                    'brokerage',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscription',
                        to='tenants.brokerage',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='subscriptions',
                        to='tenants.plan',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
