# Generated by Django 6.0.3 on 2026-06-30 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0003_covereditem_covered_item_exactly_one_parent'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(max_length=40)),
                ('occurrence_date', models.DateField()),
                ('notice_date', models.DateField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('opened', 'Aberto'),
                            ('under_analysis', 'Em análise'),
                            ('approved', 'Aprovado'),
                            ('denied', 'Negado'),
                            ('paid', 'Pago'),
                            ('closed', 'Encerrado'),
                        ],
                        default='opened',
                        max_length=20,
                    ),
                ),
                ('description', models.TextField(blank=True)),
                (
                    'claimed_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                    ),
                ),
                (
                    'approved_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                    ),
                ),
                ('ai_summary', models.TextField(blank=True)),
                (
                    'ai_summary_status',
                    models.CharField(
                        choices=[
                            ('idle', 'Pendente'),
                            ('processing', 'Processando'),
                            ('done', 'Concluído'),
                            ('error', 'Erro'),
                        ],
                        default='idle',
                        max_length=12,
                    ),
                ),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
                (
                    'covered_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='claims',
                        to='insurance.covereditem',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='claims_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='claims',
                        to='insurance.policy',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['brokerage', 'status'],
                        name='claims_clai_brokera_25009b_idx',
                    ),
                    models.Index(
                        fields=['brokerage', '-occurrence_date'],
                        name='claims_clai_brokera_7596f6_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('brokerage', 'claim_number'),
                        name='claim_unique_number_per_brokerage',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('occurrence_date__lte', models.F('notice_date')),
                        ),
                        name='claim_occurrence_le_notice',
                    ),
                ],
            },
        ),
    ]
