REPORTS = {
    'carteira': {
        'name': 'Carteira de clientes',
        'description': 'Clientes ativos e volume de apólices por cliente.',
        'icon': 'users',
        'csv_generator': 'reports.generators.csv_gen.build_carteira_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_carteira_pdf',
        'filters': ['status'],
    },
    'propostas': {
        'name': 'Propostas',
        'description': 'Propostas por período, seguradora, ramo e status.',
        'icon': 'file-text',
        'csv_generator': 'reports.generators.csv_gen.build_propostas_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_propostas_pdf',
        'filters': [
            'date_from',
            'date_to',
            'insurer_id',
            'line_of_business_id',
            'status',
        ],
    },
    'apolices': {
        'name': 'Apólices',
        'description': 'Apólices por período, seguradora, ramo e status.',
        'icon': 'shield',
        'csv_generator': 'reports.generators.csv_gen.build_apolices_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_apolices_pdf',
        'filters': [
            'date_from',
            'date_to',
            'insurer_id',
            'line_of_business_id',
            'status',
        ],
    },
    'sinistros': {
        'name': 'Sinistros',
        'description': 'Sinistros por período, status, apólice e cliente.',
        'icon': 'alert-triangle',
        'csv_generator': 'reports.generators.csv_gen.build_sinistros_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_sinistros_pdf',
        'filters': ['date_from', 'date_to', 'status'],
    },
    'renovacoes': {
        'name': 'Renovações',
        'description': 'Renovações pendentes por horizonte de vencimento.',
        'icon': 'refresh-cw',
        'csv_generator': 'reports.generators.csv_gen.build_renovacoes_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_renovacoes_pdf',
        'filters': ['horizon_days', 'status'],
    },
    'comissoes': {
        'name': 'Comissões',
        'description': 'Comissões por período, apólice, cliente e status.',
        'icon': 'dollar-sign',
        'csv_generator': 'reports.generators.csv_gen.build_comissoes_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_comissoes_pdf',
        'filters': ['date_from', 'date_to', 'status'],
    },
    'seguradoras': {
        'name': 'Seguradoras',
        'description': 'Ranking de seguradoras por prêmio de apólices ativas.',
        'icon': 'briefcase',
        'csv_generator': 'reports.generators.csv_gen.build_seguradoras_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_seguradoras_pdf',
        'filters': ['limit'],
    },
    'produtividade': {
        'name': 'Produtividade',
        'description': 'Ranking por negócios ganhos e valor estimado.',
        'icon': 'trending-up',
        'csv_generator': 'reports.generators.csv_gen.build_produtividade_csv',
        'pdf_generator': 'reports.generators.pdf_gen.build_produtividade_pdf',
        'filters': ['date_from', 'date_to', 'limit'],
    },
}
