# Generated by Django 6.0.3 on 2026-06-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'person_type',
                    models.CharField(
                        choices=[
                            ('PF', 'Pessoa Física'),
                            ('PJ', 'Pessoa Jurídica'),
                        ],
                        default='PF',
                        max_length=2,
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('document', models.CharField(max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('address_number', models.CharField(blank=True, max_length=20)),
                ('address_complement', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                (
                    'ai_summary_status',
                    models.CharField(
                        choices=[
                            ('idle', 'Pendente'),
                            ('processing', 'Processando'),
                            ('done', 'Concluído'),
                            ('error', 'Erro'),
                        ],
                        default='idle',
                        max_length=12,
                    ),
                ),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'brokerage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='tenants.brokerage',
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
                'indexes': [
                    models.Index(
                        fields=['brokerage', 'name'],
                        name='clients_cli_brokera_704036_idx',
                    ),
                    models.Index(
                        fields=['brokerage', 'is_active'],
                        name='clients_cli_brokera_8d46fe_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('brokerage', 'document'),
                        name='client_unique_document_per_brokerage',
                    )
                ],
            },
        ),
    ]
