# Generated by Django 6.0.3 on 2026-06-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_brokerage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('owner', 'Administrador'),
                    ('manager', 'Gerente'),
                    ('broker', 'Corretor'),
                    ('agent', 'Agente'),
                    ('producer', 'Produtor'),
                    ('operational', 'Operacional'),
                ],
                default='operational',
                max_length=20,
            ),
        ),
    ]
