# Generated by Django 6.0.3 on 2026-07-17 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('crm', '0001_initial'),
        ('insurance', '0004_endorsement'),
        ('insurers', '0001_initial'),
        ('partners', '0001_initial'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['brokerage', '-created_at'], name='crm_deal_brokera_c7549b_idx'),
        ),
    ]
