# Generated by Django 6.0.3 on 2026-07-08 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0004_endorsement'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('renewed', 'Renovada'), ('lost', 'Perdida'), ('not_renewed', 'Não renovada')], default='pending', max_length=15)),
                ('due_date', models.DateField(help_text='Vencimento da apólice original.')),
                ('notes', models.TextField(blank=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.brokerage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_created', to=settings.AUTH_USER_MODEL)),
                ('new_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_source', to='insurance.policy')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='insurance.policy')),
            ],
            options={
                'ordering': ('due_date',),
                'indexes': [models.Index(fields=['brokerage', 'status', 'due_date'], name='renewals_re_brokera_960bf8_idx')],
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'policy'), name='renewal_unique_per_policy')],
            },
        ),
    ]
