# Generated by Django 6.0.3 on 2026-07-17 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_endorsement'),
        ('renewals', '0001_initial'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='renewal',
            index=models.Index(fields=['brokerage', '-created_at'], name='renewals_re_brokera_61948f_idx'),
        ),
    ]
