# Generated by Django 6.0.3 on 2026-07-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0004_endorsement'),
        ('partners', '0001_initial'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_premium', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurer_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('insurer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebida'), ('paid', 'Repassada')], default='pending', max_length=10)),
                ('reference_date', models.DateField()),
                ('received_at', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.brokerage')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='insurance.policy')),
            ],
            options={
                'ordering': ('-reference_date',),
            },
        ),
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_type', models.CharField(choices=[('agent', 'Agente'), ('producer', 'Produtor')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='Percentual do prêmio direcionado ao beneficiário.', max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], default='pending', max_length=10)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_splits', to='partners.agent')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.brokerage')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='commissions.commission')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_splits', to='partners.producer')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', 'status'], name='commissions_brokera_fc6275_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', '-reference_date'], name='commissions_brokera_a60eeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionsplit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('beneficiary_type', 'agent'), ('producer__isnull', True)), models.Q(('agent__isnull', True), ('beneficiary_type', 'producer'), ('producer__isnull', False)), _connector='OR'), name='split_exactly_one_beneficiary'),
        ),
    ]
