# Generated by Django 6.0.3 on 2026-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('insurance', '0004_endorsement'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['brokerage', '-created_at'], name='commissions_brokera_776027_idx'),
        ),
    ]
