# Generated by Django 6.0.3 on 2026-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ai_summary', 'Resumo de IA'), ('report', 'Relatório'), ('report_ready', 'Relatório pronto'), ('renewal', 'Renovação'), ('system', 'Sistema')], default='system', max_length=20),
        ),
    ]
