# Generated by Django 6.0.3 on 2026-07-17 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['brokerage', '-created_at'], name='notificatio_brokera_a20ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['brokerage', 'is_read', '-created_at'], name='notificatio_brokera_f185fa_idx'),
        ),
    ]
